[book]
authors = ["Ismael Gutiérrez González"]
src = "./docs_src"
title = "Rusted PackFile Manager Documentation"

[build]
build-dir = "./docs"

[preprocessor.langtabs]
command = "mdbook-langtabs"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
additional-css = ["langtabs.css"]
additional-js = ["langtabs.js"]
