name = "rpfm_log"
crate_version = "4.7.104"
build_type = "Debug"
operating_system = """
OS: Windows
Version: 10.0.19045"""
explanation = '''
Cause: panic in a function that cannot unwind
Panic occurred in file '/rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\core\src\panicking.rs' at line 225
'''
backtrace = '''
   0:     0x7ff6c100efb0 - backtrace::backtrace::win64::trace
                               at C:\Users\Arsal Zubair\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\backtrace-0.3.76\src\backtrace\win64.rs:85
                           backtrace::backtrace::trace_unsynchronized<backtrace::capture::impl$4::create::closure_env$0>
                               at C:\Users\Arsal Zubair\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\backtrace-0.3.76\src\backtrace\mod.rs:66
   1:     0x7ff6c100f227 - backtrace::backtrace::trace<backtrace::capture::impl$4::create::closure_env$0>
                               at C:\Users\Arsal Zubair\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\backtrace-0.3.76\src\backtrace\mod.rs:53
   2:     0x7ff6c1005c7e - backtrace::capture::Backtrace::create
                               at C:\Users\Arsal Zubair\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\backtrace-0.3.76\src\capture.rs:294
   3:     0x7ff6c1005bfe - backtrace::capture::Backtrace::new
                               at C:\Users\Arsal Zubair\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\backtrace-0.3.76\src\capture.rs:259
   4:     0x7ff6c08b8900 - rpfm_log::Logger::new
                               at C:\Users\Arsal Zubair\Documents\GitHub\rpfm\rpfm_log\src\lib.rs:336
   5:     0x7ff6c08bc15b - rpfm_log::impl$0::init::closure$0
                               at C:\Users\Arsal Zubair\Documents\GitHub\rpfm\rpfm_log\src\lib.rs:279
   6:     0x7ff6c2846661 - std::panicking::panic_with_hook
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\std\src\panicking.rs:833
   7:     0x7ff6c28463f9 - std::panicking::panic_handler::closure$0
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\std\src\panicking.rs:691
   8:     0x7ff6c283fb0f - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::panic_handler::closure_env$0,never$>
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\std\src\sys\backtrace.rs:182
   9:     0x7ff6c282a8be - std::panicking::panic_handler
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\std\src\panicking.rs:689
  10:     0x7ff6c2f27b07 - core::panicking::panic_nounwind_fmt
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\core\src\intrinsics\mod.rs:2432
  11:     0x7ff6c2f27a81 - core::panicking::panic_nounwind
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\core\src\panicking.rs:225
  12:     0x7ff6c2f27c36 - core::panicking::panic_cannot_unwind
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\core\src\panicking.rs:337
  13:     0x7ff6bfb0aa03 - qt_core::impl$767::new::ffi_callback<rpfm_ui::packfile_contents_ui::slots::impl$0::new::closure_env$52>
                               at C:\Users\Arsal Zubair\Documents\GitHub\rpfm\3rdparty\src\ritual\output\out\qt_core\src\lib.rs:170778
  14:     0x7ff973790430 - _CxxFrameHandler3
  15:     0x7ff97378342d - is_exception_typeof
  16:     0x7ff9895d1d46 - RtlCaptureContext2
  17:     0x7ff6bfb0a9d4 - qt_core::impl$767::new::ffi_callback<rpfm_ui::packfile_contents_ui::slots::impl$0::new::closure_env$52>
                               at C:\Users\Arsal Zubair\Documents\GitHub\rpfm\3rdparty\src\ritual\output\out\qt_core\src\lib.rs:170782
  18:     0x7ff8dfcf59cd - QObject::qt_static_metacall
  19:     0x7ff8dfcf8734 - QMetaObject::activate
  20:     0x7ff8e05c17b1 - QAction::activate
  21:     0x7ff8df795b4f - QMenu::actionGeometry
  22:     0x7ff8df79591c - QMenu::actionGeometry
  23:     0x7ff8df79c3c3 - QMenu::mouseReleaseEvent
  24:     0x7ff8df628034 - QWidget::event
  25:     0x7ff8df79722a - QMenu::event
  26:     0x7ff8df5e32c6 - QApplicationPrivate::notify_helper
  27:     0x7ff8df5e1481 - QApplication::notify
  28:     0x7ff8dfcb5911 - QCoreApplication::notifyInternal2
  29:     0x7ff8df5e5cd8 - QApplicationPrivate::sendMouseEvent
  30:     0x7ff8df64e6ce - QWidgetRepaintManager::updateStaticContentsSize
  31:     0x7ff8df64c5e8 - QWidgetRepaintManager::updateStaticContentsSize
  32:     0x7ff8df5e32c6 - QApplicationPrivate::notify_helper
  33:     0x7ff8df5e240d - QApplication::notify
  34:     0x7ff8dfcb5911 - QCoreApplication::notifyInternal2
  35:     0x7ff8e021e95f - QGuiApplicationPrivate::processMouseEvent
  36:     0x7ff8e027ecab - QWindowSystemInterface::sendWindowSystemEvents
  37:     0x7ff8dfe4729e - QEventDispatcherWin32::processEvents
  38:     0x7ff8e0549809 - QWindowsGuiEventDispatcher::processEvents
  39:     0x7ff8dfcbc274 - QEventLoop::exec
  40:     0x7ff8df79761e - QMenu::exec
  41:     0x7ff8df79745b - QMenu::exec
  42:     0x7ff6c0239d83 - qt_widgets::QMenu::exec_1a_mut
                               at C:\Users\Arsal Zubair\Documents\GitHub\rpfm\3rdparty\src\ritual\output\out\qt_widgets\src\lib.rs:65991
                           rpfm_ui::packfile_contents_ui::slots::impl$0::new::closure$8
                               at C:\Users\Arsal Zubair\Documents\GitHub\rpfm\rpfm_ui\src\packfile_contents_ui\slots.rs:332
  43:     0x7ff6bfd8998f - qt_widgets::impl$313::new::ffi_callback<rpfm_ui::packfile_contents_ui::slots::impl$0::new::closure_env$8>
                               at C:\Users\Arsal Zubair\Documents\GitHub\rpfm\3rdparty\src\ritual\output\out\qt_widgets\src\lib.rs:133480
  44:     0x7ff8dfcf59cd - QObject::qt_static_metacall
  45:     0x7ff8dfcf8734 - QMetaObject::activate
  46:     0x7ff8df6260ba - QWidget::customContextMenuRequested
  47:     0x7ff8df628550 - QWidget::event
  48:     0x7ff8df687133 - QFrame::event
  49:     0x7ff8df8a2845 - QAbstractItemView::viewportEvent
  50:     0x7ff8dfcb8457 - QCoreApplicationPrivate::sendThroughObjectEventFilters
  51:     0x7ff8df5e32ab - QApplicationPrivate::notify_helper
  52:     0x7ff8df5e1b41 - QApplication::notify
  53:     0x7ff8dfcb5911 - QCoreApplication::notifyInternal2
  54:     0x7ff8df64cfe6 - QWidgetRepaintManager::updateStaticContentsSize
  55:     0x7ff8df64c90b - QWidgetRepaintManager::updateStaticContentsSize
  56:     0x7ff8df5e32c6 - QApplicationPrivate::notify_helper
  57:     0x7ff8df5e240d - QApplication::notify
  58:     0x7ff8dfcb5911 - QCoreApplication::notifyInternal2
  59:     0x7ff8e026ebec - QWindowPrivate::maybeSynthesizeContextMenuEvent
  60:     0x7ff8df64ee0d - QWidgetRepaintManager::updateStaticContentsSize
  61:     0x7ff8df64c5e8 - QWidgetRepaintManager::updateStaticContentsSize
  62:     0x7ff8df5e32c6 - QApplicationPrivate::notify_helper
  63:     0x7ff8df5e240d - QApplication::notify
  64:     0x7ff8dfcb5911 - QCoreApplication::notifyInternal2
  65:     0x7ff8e021e95f - QGuiApplicationPrivate::processMouseEvent
  66:     0x7ff8e027ecab - QWindowSystemInterface::sendWindowSystemEvents
  67:     0x7ff8dfe4729e - QEventDispatcherWin32::processEvents
  68:     0x7ff8e0549809 - QWindowsGuiEventDispatcher::processEvents
  69:     0x7ff8dfcbc274 - QEventLoop::exec
  70:     0x7ff8dfcb3faa - QCoreApplication::exec
  71:     0x7ff6bfe0b88c - qt_widgets::QApplication::exec
                               at C:\Users\Arsal Zubair\Documents\GitHub\rpfm\3rdparty\src\ritual\output\out\qt_widgets\src\lib.rs:22226
                           rpfm_ui::main::closure$0
                               at C:\Users\Arsal Zubair\Documents\GitHub\rpfm\rpfm_ui\src\main.rs:235
  72:     0x7ff6bfd8a56d - qt_widgets::QApplication::init<rpfm_ui::main::closure_env$0>
                               at C:\Users\Arsal Zubair\Documents\GitHub\rpfm\3rdparty\src\ritual\output\out\qt_widgets\src\impl_q_application.rs:33
  73:     0x7ff6c004f7ad - rpfm_ui::main
                               at C:\Users\Arsal Zubair\Documents\GitHub\rpfm\rpfm_ui\src\main.rs:228
  74:     0x7ff6bf8e6d4b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\core\src\ops\function.rs:250
  75:     0x7ff6bfdd728e - core::hint::black_box
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\core\src\hint.rs:482
                           std::sys::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\std\src\sys\backtrace.rs:166
  76:     0x7ff6bff8b251 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\std\src\rt.rs:206
  77:     0x7ff6c282eb4f - std::rt::lang_start_internal::closure$0
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\std\src\rt.rs:175
                           std::panicking::catch_unwind::do_call
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\std\src\panicking.rs:581
                           std::panicking::catch_unwind
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\std\src\panicking.rs:544
                           std::panic::catch_unwind
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\std\src\panic.rs:359
                           std::rt::lang_start_internal
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\std\src\rt.rs:171
  78:     0x7ff6bff8b23a - std::rt::lang_start<tuple$<> >
                               at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library\std\src\rt.rs:205
  79:     0x7ff6c0050739 - main
  80:     0x7ff6c2f23d08 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
                           __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  81:     0x7ff989097374 - BaseThreadInitThunk
  82:     0x7ff98957cc91 - RtlUserThreadStart
'''
