[package]
name = "rpfm"
version = "2.4.1"
build = "build.rs"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
description = "Launcher of RPFM, to allow autorestarting on update."
edition = "2018"

# Windows resources support.
[target.'cfg(windows)'.build-dependencies]
winres = "^0.1"
