name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache build target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build libs and server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p rpfm_lib -p rpfm_extensions -p rpfm_ipc -p rpfm_log -p rpfm_server

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p rpfm_lib -p rpfm_extensions -p rpfm_ipc -p rpfm_log -p rpfm_server
