name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Build rpfm-lib
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --lib
      
      - name: Build rpfm-cli
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --bin rpfm_cli

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib
