name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache build target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build rpfm-lib and rpfm-extensions
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --lib --exclude rpfm_ui_common
      
      - name: Build rpfm-cli
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --bin rpfm_cli

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --lib --exclude rpfm_ui_common
